mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rental.urls')),
    path('users/', include('registration.backends.simple.urls')),
]

rental/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
from .models import Book
app_name = 'books'

urlpatterns = [
    path('', view=views.HomePageView.as_view(), name='home_page'),
    path('books', view=views.BookListView.as_view(), name='books'),
    path('book/<slug:slug>', views.BookDetailView.as_view(), name='bookDetail'),
    path('confirm-rent-a-book/<slug:slug>', views.confirm_rent_viewb, name="confirm_rent_viewb"),
    path('book/rent-book/<slug:slug>', views.rent_book_view, name='rent_book'),
    path('book/return-book/<slug:slug>', views.return_book_view, name='return_book'),
    path('editb/<int:pk>', view=views.BookUpdateView.as_view(), name='book_edit'),
    path('newb', view=views.BookCreateView.as_view(), name='book_new'),
    path('deleteb/<int:pk>', view=views.BookDeleteView.as_view(), name='book_delete'),
    path('search-book-results/', view=views.SearchBookListView.as_view(), name='searchb'),
    path('films', view=views.FilmListView.as_view(), name='films'),
    path('film/<slug:slug>', views.FilmDetailView.as_view(), name='filmDetail'),
    path('confirm-rent-a-film/<slug:slug>', views.f_confirm_rent_view, name="f_confirm_rent_view"),
    path('film/rent-film/<slug:slug>', views.rent_film_view, name='rent_film'),
    path('film/return-film/<slug:slug>', views.return_film_view, name='return_film'),
    path('editf/<int:pk>', view=views.FilmUpdateView.as_view(), name='film_edit'),
    path('newf', view=views.FilmCreateView.as_view(), name='film_new'),
    path('deletef/<int:pk>', view=views.FilmDeleteView.as_view(), name='film_delete'),
    path('search-film-results/', view=views.SearchFilmListView.as_view(), name='searchf'),
    path('CDs', view=views.CDListView.as_view(), name='CDs'),
    path('cd/<slug:slug>', views.CDDetailView.as_view(), name='cdDetail'),
    path('confirm-rent-a-cd/<slug:slug>', views.cd_confirm_rent_view, name="cd_confirm_rent_view"),
    path('cd/rent-cd/<slug:slug>', views.rent_cd_view, name='rent_cd'),
    path('cd/return-cd/<slug:slug>', views.return_cd_view, name='return_cd'),
    path('editcd/<int:pk>', view=views.CDUpdateView.as_view(), name='cd_edit'),
    path('newcd', view=views.CDCreateView.as_view(), name='cd_new'),
    path('deletecd/<int:pk>', view=views.CDDeleteView.as_view(), name='cd_delete'),
    path('search-cd-results/', view=views.SearchCDListView.as_view(), name='searchcd'),
    path('stats/', view=views.RankingView.as_view(), name='ranking')

]

rental/models.py
from datetime import datetime, timedelta
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify
from django.db.models import Count
from django.core.exceptions import ValidationError

class BookGenre(models.Model):
    name = models.CharField(
        max_length=50,
        help_text="Enter a book genre"
    )
    slug = models.SlugField(unique=True)

    popularity = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(BookGenre, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "BookGenres"


class Book(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    author = models.CharField(max_length=50)
    genre = models.ForeignKey('BookGenre', on_delete=models.PROTECT, null=True)
    ISBN = models.CharField(max_length=13, unique=True)
    book_amount = models.IntegerField(default=0)
    popularity = models.IntegerField(default=0)


    class Meta:
        unique_together = ('author','title','genre',)


    def __str__(self):
        return self.title


    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Book, self).save(*args, **kwargs)



class BookRentHistory(models.Model):
    book = models.ForeignKey(
        Book, on_delete=models.PROTECT, editable=False)
    user = models.ForeignKey(
        User, on_delete=models.PROTECT, editable=False, related_name='books')
    rent_date = models.DateField(auto_now_add=True, editable=False)
    back_date = models.DateField(
        default=datetime.now()+timedelta(days=30))

    @property
    def how_many_days(self):
        return str(self.back_date - datetime.now().date())[:2]



class FilmGenre(models.Model):
    name = models.CharField(
        max_length=50,
        help_text="Enter a film genre"
    )
    slug = models.SlugField(unique=True)

    popularity = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(FilmGenre, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "FilmGenres"



class Film(models.Model):
    director = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)
    genre = models.ForeignKey('FilmGenre', on_delete=models.PROTECT, null=True)
    length = models.DecimalField(max_digits=3, decimal_places=2)
    film_amount = models.IntegerField(default=0)
    popularity = models.IntegerField(default=0)

    class Meta:
        unique_together = ('director', 'title', 'length',)

    def __str__(self):
        return self.title

    def clean(self, *args, **kwargs):
        genres = FilmGenre.objects.annotate(num_films=Count('film')).order_by('-num_films')
        if genres:
            diff = Film.objects.filter(genre=self.genre).count() - genres[0].num_films
            if diff > 3 :
                raise ValidationError(_('Liczby roznych filmow danego gatunku w ramach calej kolekcji moga roznic sie o 3!'))
        super(Film, self).clean(*args, **kwargs)


    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        self.full_clean()
        super(Film, self).save(*args, **kwargs)



class FilmRentHistory(models.Model):
    film = models.ForeignKey(
        Film, on_delete=models.PROTECT, editable=False)
    user = models.ForeignKey(
        User, on_delete=models.PROTECT, editable=False, related_name='films')
    rent_date = models.DateField(auto_now_add=True, editable=False)
    back_date = models.DateField(
        default=datetime.now()+timedelta(days=30))

    @property
    def how_many_days(self):
        return str(self.back_date - datetime.now().date())[:2]


class CDGenre(models.Model):
    name = models.CharField(
        max_length=50,
        help_text="Enter a CD genre"
    )
    slug = models.SlugField(unique=True)

    popularity = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(CDGenre, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "CDGenres"



class CD(models.Model):
    band = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    slug = models.SlugField(unique=True)
    genre = models.ForeignKey('CDGenre', on_delete=models.PROTECT, null=True)
    length = models.DecimalField(max_digits=3, decimal_places=2)
    CD_amount = models.IntegerField(default=0)
    tracks = models.TextField(max_length=300)
    popularity = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def clean(self, *args, **kwargs):
        ct = CD.objects.filter(genre=self.genre).filter(tracks=self.tracks).count()
        if ct:
            if ct > 1:
                 raise ValidationError(
                        'w ramach jednego gatunku nie możemy oferować dwóch płyt o tej samej liście utworów')

        mydiscog = CD.objects.filter(band=self.band).values('genre').distinct().count()
        if mydiscog:
            if mydiscog > 2:
                 raise ValidationError('płyty danego zespołu mogą być oferowane tylko w dwóch gatunkach!')
        super(CD, self).clean(*args, **kwargs)


    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        self.full_clean()
        super(CD, self).save(*args, **kwargs)



class CDRentHistory(models.Model):
    cd = models.ForeignKey(
        CD, on_delete=models.PROTECT, editable=False)
    user = models.ForeignKey(
        User, on_delete=models.PROTECT, editable=False, related_name='CDs')
    rent_date = models.DateField(auto_now_add=True, editable=False)
    back_date = models.DateField(
        default=datetime.now()+timedelta(days=30))

    @property
    def how_many_days(self):
        return str(self.back_date - datetime.now().date())[:2]



# Create your models here.

rental/forms.py
from django import forms

from .models import Book

from .models import Film

from .models import CD


class BookForm(forms.ModelForm):

    class Meta:
        model = Book
        fields = ('title', 'author', 'genre','ISBN','book_amount')

class FilmForm(forms.ModelForm):

    class Meta:
        model = Film
        fields = ('title', 'director', 'genre','length','film_amount')

class CDForm(forms.ModelForm):

    class Meta:
        model = CD
        fields = ('title', 'band', 'genre','length','CD_amount','tracks')

rental/templates/rental/CD_list.html
{% extends 'rental/base.html' %}

{% block content %}
{% for CD in CDs %}
<div>
    <h2>Tytuł: {{CD.title}}</h2>
    <p>Zespół: {{CD.band}}</p>
    <p>Gatunek: {{CD.genre}}</p>
    <p>Czas trwania: {{CD.length}}</p>
    <p>Utwory: {{CD.tracks}}</p>
    <p>ID: {{CD.pk}}</p>
</div>
{% endfor %}
{% endblock %}

rental/templates/rental/CDs.html
{% extends "rental/base.html" %}
{% block content %}
<p>
    <h1 class="text-center"> CDs </h1>
    <h5 class="mt-3"><strong>Search most popular CDs by the genre: </strong></h5>

    <form class="searchForm" action="{% url 'books:searchcd' %}" method="GET">
        <div class="form-group row">
            <input class="form-control col-md-7" required="required" name="q" type="text" placeholder="Write the genre">
            <span class="col-md-1"></span>
            <button type="submit" class="btn btn-primary form-control col-md-2">Search</button>
        </div>
    </form>
</p>
<hr class="my-4">
<a href="{% url "books:cd_new" %}">+ New CD</a>
<h3>Most popular CDs:</h3>
<div class="row ">
    {% for cd in top_3_CDs %}
    <div class="col-md-4 ">
        <div>
            <h5>{{ cd.title }}</h5>
            <h6>{{ cd.band }}</h6>
            <a href="{% url 'books:cdDetail' slug=cd.slug %}"><button class="btn btn-primary btn-xs">CD details</button></a>
        </div>
    </div>
    {% endfor %}
</div>
<h3>Recent added CDs:</h3>
<div class="row">
    {% for cd in cd_list %}
    <div class="col-md-4 ">
        <div >
            <h5>{{ cd.title }}</h5>
            <h6>{{ cd.band }}</h6>
            <a href="{% url 'books:cdDetail' slug=cd.slug %}"><button class="btn btn-primary btn-xs">CD details</button></a>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock content %}

rental/templates/rental/base.html
{% load static %}
<html>
    <head>
        <title>Rental</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/rental.css' %}">
        <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    </head>
    <body>
    <div class="rental vertical-center">
        <div class="container    ">
                    {% block content %}
                    {% endblock %}
        </div>
    </div>
    </body>
</html>

rental/templates/rental/book_list.html
{% extends 'rental/base.html' %}

{% block content %}
{% for book in books %}
<div>
    <h2>Tytuł: {{book.title}}</h2>
    <p>Reżyser: {{book.author}}</p>
    <p>Gatunek: {{book.ISBN}}</p>
    <p>ID: {{book.pk}}</p>
</div>
{% endfor %}
{% endblock %}

rental/templates/rental/book_search_result.html
{% extends "rental/base.html" %}
{% block content %}
<h2>Search results for: "{{ request.GET.q }}":</h2>
<div class="row">
    {% if book_list %}
    {% for book in book_list %}
    <div class="col-md-4 ">
        <div>
            <h5>{{ book.title }}</h5>
            <h6>{{ book.author }}</h6>
            <h6>popularity : {{ book.popularity }}</h6>
            <a href="{% url 'books:bookDetail' slug=book.slug %}"><button class="btn btn-primary btn-xs">Book details</button></a>
        </div>

    </div>
    {% endfor %}
    {% else %}
    <h5 style="margin-left:30px;"> We don't have that book :/</h5>
    {% endif %}


</div>
{% endblock content %}

rental/templates/rental/cd_detail.html
{% extends "rental/base.html" %}
{% block content %}
<div class="row mx-auto">
    <div class=" col-md-6">
        {% if cd.CD_amount > 0 %}
        <h5><strong>Available CD amount :</strong> {{ cd.CD_amount }}</h5>
            {% if user.is_authenticated %}
            <a href="{% url 'books:cd_confirm_rent_view' slug=cd.slug %}"><button class="btn btn-primary btn-xs">Rent</button></a>
            <a href="{% url 'books:cd_edit' cd.id %}"><button type="button" >Zmień</button></a>
            <a href="{% url 'books:cd_delete' cd.id %}"><button type="button">Usuń</button></a>
            {% else %}
            <a href="{% url 'books:cd_confirm_rent_view' slug=cd.slug %}"><button class="btn btn-primary btn-xs">Login to rent
                    CD</button></a>
            {% endif %}
        {% else %}
        <h5><strong>Available CD amount : </strong>none</h5>
        {% endif %} <br>
    </div>
    <div class=" col-md-6">
        <h5><strong>Title:</strong>  {{ cd.title }} </h5>
        <h5><strong>Band:</strong> {{ cd.band }}</h5>
        <h5><strong>Genre:</strong> {{ cd.genre }}</h5>
        <h5><strong>Popularity:</strong> {{ cd.popularity }}</h5>
        </div>
    </div>



</div>









{% endblock content %}

rental/templates/rental/cd_form.html
{% extends 'rental/base.html' %}

{% block content %}
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit"value="Zapisz">
    </form>
{% endblock %}

rental/templates/rental/cd_search_result.html
{% extends "rental/base.html" %}
{% block content %}
<h2>Search results for: "{{ request.GET.q }}":</h2>
<div class="row lastBooksContainer">
    {% if cd_list %}
    {% for cd in cd_list %}
    <div class="col-md-4 bookCard">
        <div class="cardBorder">
            <h5>{{ cd.title }}</h5>
            <h6>{{ cd.band }}</h6>
            <h6>popularity : {{ cd.popularity }}</h6>
            <a href="{% url 'books:cdDetail' slug=cd.slug %}"><button class="btn btn-primary btn-xs">Book details</button></a>
        </div>

    </div>
    {% endfor %}
    {% else %}
    <h5 style="margin-left:30px;"> We don't have that book :/</h5>
    {% endif %}


</div>
{% endblock content %}

rental/templates/rental/f_confirm_rent_view.html
{% extends "rental/base.html" %}
{% block content %}

<h3>Are you sure tha you want to rent this book? </h3>
<h5><strong>Title:</strong> {{ film.title }}</h5>
<h5><strong>Author:</strong> {{ film.director }}</h5>
<a href="{% url 'books:rent_film' slug=film.slug %}"><button class="btn btn-success btn-xs">Rent film</button></a>
<a href="{% url 'books:filmDetail' slug=film.slug %}"><button class="btn btn-info btn-xs">Return</button></a>
{% endblock content %}

rental/templates/rental/film_confirm_delete.html
{% extends 'rental/base.html' %}

{% block content %}
    <form method="post">
      {% csrf_token %}
      <div class="alert alert-warning" role="alert">
        Czy jesteś pewny usunięcia {{ object }} ?
      </div>
      <input type="submit" value="Tak, usuń ten film" />
      <a class="btn btn-success" href="{% url 'books:films' %}">Nie</a>
    </form>
  </div>
</div>
{% endblock %}

rental/templates/rental/film_form.html
{% extends 'rental/base.html' %}

{% block content %}
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit"value="Zapisz">
    </form>
{% endblock %}

rental/templates/rental/film_list.html
{% extends 'rental/base.html' %}

{% block content %}
{% for film in films %}
<div>
    <h2>Tytuł: {{film.title}}</h2>
    <p>Reżyser: {{film.director}}</p>
    <p>Gatunek: {{film.genre}}</p>
    <p>Czas trwania: {{film.length}}</p>
    <p>ID: {{film.pk}}</p>
</div>
{% endfor %}
{% endblock %}

rental/templates/rental/films.html
{% extends "rental/base.html" %}
{% block content %}
<p>
    <h1 class="text-center"> Films </h1>
<h5 class="mt-3"><strong>Search most popular films by the genre:</strong> </h5>
    <form class="searchForm" action="{% url 'books:searchf' %}" method="GET">
        <div class="form-group row">
            <input class="form-control col-md-7" required="required" name="q" type="text" placeholder="Write the genre">
            <span class="col-md-1"></span>
            <button type="submit" class="btn btn-primary form-control col-md-2">Search</button>
        </div>
    </form>
</p>
<hr class="my-4">
<a href="{% url "books:film_new" %}">+ New film</a>
<h3>Most popular films:</h3>
<div class="row lastBooksContainer">
    {% for film in top_3_films %}
    <div class="col-md-4 bookCard">
        <div class="cardBorder">
            <h5>{{ film.title }}</h5>
            <h6>{{ film.director }}</h6>
            <a href="{% url 'books:filmDetail' slug=film.slug %}"><button class="btn btn-primary btn-xs">Film details</button></a>
        </div>
    </div>
    {% endfor %}
</div>
<h3>Recent added films:</h3>
<div class="row lastBooksContainer">
    {% for film in film_list %}
    <div class="col-md-4 bookCard">
        <div class="cardBorder">
            <h5>{{ film.title }}</h5>
            <h6>{{ film.director }}</h6>
            <a href="{% url 'books:filmDetail' slug=film.slug %}"><button class="btn btn-primary btn-xs">Film details</button></a>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock content %}

rental/templates/rental/main_page.html
{% extends 'rental/base.html' %}

{% block content %}
<p>
<h1 class="text-center"> It's a main page! </h1>
</p>
<div class="row mx-auto " >

    <div class="col-12 col-md-8 ">
        {% if user.is_authenticated %}
        <h2>Your rented books:</h2>
        <table class='table table-bordered' style="width:100%" >
            <tr>
                <th>Title</th>
                <th>Rent date</th>
                <th>Data of return</th>
                <th>Days</th>
                <th>Action</th>
            </tr>
            {% for book in user.books.all %}
                <tr>
                    <td>{{ book.book.title }}</td>
                    <td>{{ book.rent_date|date:"d-m-Y" }}</td>
                    <td>{{ book.back_date|date:"d-m-Y" }}</td>
                    <td>{{ book.how_many_days }}</td>
                    {% if book.how_many_days > '0:' %}
                        <td><a href="{% url 'books:return_book' slug=book.book.slug %}">Return it</a>
                        </td>
                    {% else %}
                        <td>Returned</td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
            <h2>Your rented films:</h2>
        <table class="table table-bordered" style="width:100%" id="films">
            <tr>
                <th>Title</th>
                <th>Rent date</th>
                <th>Data of return</th>
                <th>Days</th>
                <th>Action</th>
            </tr>
            {% for film in user.films.all %}
                <tr>
                    <td>{{ film.film.title }}</td>
                    <td>{{ film.rent_date|date:"d-m-Y" }}</td>
                    <td>{{ film.back_date|date:"d-m-Y" }}</td>
                    <td>{{ film.how_many_days }}</td>
                    {% if film.how_many_days > '0:' %}
                        <td><a href="{% url 'books:return_film' slug=film.film.slug %}">Return it</a>
                        </td>
                    {% else %}
                        <td>Returned</td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
            <h2>Your rented CDs:</h2>
        <table class="table table-bordered" style="width:100%" id="CDs">
            <tr>
                <th>Title</th>
                <th>Rent date</th>
                <th>Data of return</th>
                <th>Days</th>
                <th>Action</th>
            </tr>
            {% for cd in user.CDs.all %}
                <tr>
                    <td>{{ cd.cd.title }}</td>
                    <td>{{ cd.rent_date|date:"d-m-Y" }}</td>
                    <td>{{ cd.back_date|date:"d-m-Y" }}</td>
                    <td>{{ cd.how_many_days }}</td>
                    {% if cd.how_many_days > '0:' %}
                        <td><a href="{% url 'books:return_cd' slug=cd.cd.slug %}">Return it</a>
                        </td>
                    {% else %}
                        <td>Returned</td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
      {% endif %}
    </ul>

    </div>
    <div class="col-6 col-md-4 ">
        <h2 class="pl-5">Menu:</h2>
        <ul class="ml-0 bg-white">
            <li><a href="{% url 'books:books' %}">Books</a></li>
            <li><a href="{% url 'books:films' %}">Films</a></li>
             <li><a href="{% url 'books:CDs' %}">CDs</a></li>
            <li><a href="{% url 'books:ranking' %}">Ranking</a></li>
          {% if not user.is_authenticated %}
            <li><a href="{% url 'auth_login' %}">Login</a></li>
            <li><a href="{% url 'registration_register' %}">Register</a></li>
          {% else %}
            <li><a href="{% url 'auth_logout' %}">Logout</a></li>
            {% endif %}
        </ul>
    </div>
</div>
{% endblock %}